### ISSUE TITLE
Objective of androidManifestFile in gradle config

### ISSUE THREAD

**Issue by fikr4n** [ddekanski/SpiceAnnotations#3]
Hi, this example is very helpful, thank you. However I cannot compile it since the gradle version is not supported anymore. So [I forked your work](https://github.com/fikr4n/SpiceAnnotations) and update it to make the compiler *happy* (and also make the Spice request simpler and more general, avoiding creating new class for each request, like this `spiceManager.newRequest(User.class, (r) -> r.getUser(pageName))`).

The problem was that after updating, this line caused error:

```groovy
apt {
    arguments {
        androidManifestFile variant.processResources.manifestFile
    }
}
```

Although it can be replaced by:

```groovy
apt {
    arguments {
        androidManifestFile variant.outputs[0].processResources.manifestFile
    }
}
```

I am not sure if it is equivalent or not. So, what is the actual objective of `androidManifestFile variant.processResources.manifestFile`? It seems okay if I delete (comment) those lines since [the example](https://github.com/androidannotations/androidannotations/wiki/Building-Project-Gradle) just left it blank. However I am not sure, so that I ask you.

Thank you

**Comment by ddekanski** [comment]
Hi Fikrul,

Thanks for your interest in my (a bit outdated) example!

It's true I haven't had time to keep the project up to date with the ever-changing AS versions, so I added you as a collaborator so that you can commit your changes (since you've already invested your precious time in fixing the code).

EDIT:
The androidManifestFile argument definition was required by the android-apt plugin that is used to include AA in Android Studio projects: https://blog.jayway.com/2014/12/19/androidannotations-setup-android-studio/. Now I see it's not required anymore, so indeed you can skip it altogether.

Thanks,

Daniel.

**Comment by fikr4n** [comment]
Thank you. It's just a little experiment I'd love to write. However if you like it, I could make a PR. I didn't make any PR because the change is too much, I doubt it's out of this repo's intention 😆. Besides that, I am still not sure about using lambda, it tends to cause memory leak if not used properly ([reference](http://stackoverflow.com/a/28449928/1197317)).

**Comment by fikr4n** [comment]
I added a piece of code to check for possibility of memory leak in [my fork](https://github.com/fikr4n/SpiceAnnotations). Not sure should I merge it to master branch or just create a new branch to let it as an *alternative flavour*.
